include:
  # 1. The Prospector Dongle (XIAO BLE)
  - board: xiao_ble
    shield: totem_left prospector_adapter
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DMIRYOKU_MAPPING=TOTEM
    
  # 2. Totem Left Half (Peripheral)
  - board: xiao_ble
    shield: totem_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DMIRYOKU_MAPPING=TOTEM

  # 3. Totem Right Half (Peripheral)
  - board: xiao_ble
    shield: totem_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DMIRYOKU_MAPPING=TOTEM
