name: 'Build Prospector Totem'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      include: |
        # 1. The Prospector Dongle (Central)
        - board: xiao_ble
          shield: prospector_adapter totem_left
          kconfig: |
            CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
            CONFIG_ZMK_DISPLAY=y
            CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
          cmake_args: -DMIRYOKU_MAPPING=TOTEM

        # 2. Totem Left (Peripheral)
        - board: xiao_ble
          shield: totem_left
          kconfig: |
            CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
          cmake_args: -DMIRYOKU_MAPPING=TOTEM

        # 3. Totem Right (Peripheral)
        - board: xiao_ble
          shield: totem_right
          kconfig: |
            CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
          cmake_args: -DMIRYOKU_MAPPING=TOTEM
